{
  "comments": [
    {
      "key": {
        "uuid": "3a961159_1c07a1ca",
        "filename": "jenkins/__init__.py",
        "patchSetId": 5
      },
      "lineNbr": 218,
      "author": {
        "id": 1054
      },
      "writtenOn": "2015-01-13T20:02:03Z",
      "side": 1,
      "message": "Note that this will now raise an exception where previously it did not.",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_d7a33241",
        "filename": "jenkins/__init__.py",
        "patchSetId": 5
      },
      "lineNbr": 218,
      "author": {
        "id": 679
      },
      "writtenOn": "2015-01-13T20:49:21Z",
      "side": 1,
      "message": "There are two ways I can deal with this: I could let the exception continue to be raised, or I could wrap in a try/except and maintain the previous calling convention.  Which do you think is best?",
      "parentUuid": "3a961159_1c07a1ca",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_4f1eca0e",
        "filename": "jenkins/__init__.py",
        "patchSetId": 5
      },
      "lineNbr": 218,
      "author": {
        "id": 1054
      },
      "writtenOn": "2015-01-13T21:56:26Z",
      "side": 1,
      "message": "I\u0027ll have to leave that to the project maintainer, but I\u0027m guessing that for this to raise an exception it\u0027s an api change and probably requires some notes added to let consumers know along with a version bump.",
      "parentUuid": "3a961159_d7a33241",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_3caffd7e",
        "filename": "jenkins/__init__.py",
        "patchSetId": 5
      },
      "lineNbr": 220,
      "author": {
        "id": 1054
      },
      "writtenOn": "2015-01-13T20:02:03Z",
      "side": 1,
      "message": "I believe that previously if the job didn\u0027t exist, response would be empty here so this method used to return None.",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_3c57fdcb",
        "filename": "jenkins/__init__.py",
        "patchSetId": 5
      },
      "lineNbr": 526,
      "author": {
        "id": 1054
      },
      "writtenOn": "2015-01-13T20:02:03Z",
      "side": 1,
      "message": "Just realised this will now trigger an exception, which is not the same as before. Previously it returned False if the job didn\u0027t exist.",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_1cd5e11a",
        "filename": "jenkins/__init__.py",
        "patchSetId": 5
      },
      "lineNbr": 538,
      "author": {
        "id": 1054
      },
      "writtenOn": "2015-01-13T20:02:03Z",
      "side": 1,
      "message": "The fact that this call will result in an exception if the job does not exist makes the raise statement below redundant.",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_fc29f5f2",
        "filename": "tests/test_jenkins.py",
        "patchSetId": 5
      },
      "lineNbr": 184,
      "author": {
        "id": 1054
      },
      "writtenOn": "2015-01-13T20:04:56Z",
      "side": 1,
      "message": "Two tests below look like they should be potentially updated have jenkins_open return a 404.",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_024c9a75",
        "filename": "tests/test_jenkins.py",
        "patchSetId": 5
      },
      "lineNbr": 184,
      "author": {
        "id": 679
      },
      "writtenOn": "2015-01-13T20:54:04Z",
      "side": 1,
      "message": "Could you comment on the second test, so I can see which one you mean?  I can see how test_assert_job_exists__job_missing() needs to be amended, but test_assert_job_exists__job_exists()  looks like it\u0027s intended for the non-404 caseâ€¦",
      "parentUuid": "3a961159_fc29f5f2",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3a961159_1d65db1c",
        "filename": "tests/test_jenkins.py",
        "patchSetId": 5
      },
      "lineNbr": 184,
      "author": {
        "id": 1054
      },
      "writtenOn": "2015-01-13T21:48:15Z",
      "side": 1,
      "message": "Ah, sorry, I was wrong about the second one. Due to comment and run!",
      "parentUuid": "3a961159_024c9a75",
      "revId": "2fb0d53f634093a5dd1a70791b5116dbc8607075",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}