{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "8f7bcd02_a0b5c316",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 35866
      },
      "writtenOn": "2023-03-21T09:14:14Z",
      "side": 1,
      "message": "recheck\nThe tests are failing for no package \u0027python-dev\u0027 and file/directory \u0027tox\u0027 exists. This is not related to the changes I made. Please recheck.",
      "revId": "f86c9161209f1a13cf91a33f706b03734b76f100",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}