{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "8f7bcd02_a0b5c316",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 35866
      },
      "writtenOn": "2023-03-21T09:14:14Z",
      "side": 1,
      "message": "recheck\nThe tests are failing for no package \u0027python-dev\u0027 and file/directory \u0027tox\u0027 exists. This is not related to the changes I made. Please recheck.",
      "revId": "f86c9161209f1a13cf91a33f706b03734b76f100",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "03c97e39_e7c162a1",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 2475
      },
      "writtenOn": "2023-03-21T09:24:49Z",
      "side": 1,
      "message": "Indeed, the test jobs are broken and we have a fix pending at https://review.opendev.org/c/jjb/python-jenkins/+/865776 ;)",
      "revId": "f86c9161209f1a13cf91a33f706b03734b76f100",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "86337004_595e4a1b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 2475
      },
      "writtenOn": "2023-03-21T10:37:11Z",
      "side": 1,
      "message": "recheck after CI fix https://review.opendev.org/c/jjb/python-jenkins/+/865776",
      "revId": "f86c9161209f1a13cf91a33f706b03734b76f100",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "244508c1_ffdd1465",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 35866
      },
      "writtenOn": "2023-03-21T11:00:23Z",
      "side": 1,
      "message": "Thank you for informing me about this. Do you happen to have any information regarding when it will be resolved?",
      "revId": "f86c9161209f1a13cf91a33f706b03734b76f100",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3e46ae6e_fd285879",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 2475
      },
      "writtenOn": "2023-03-21T11:06:24Z",
      "side": 1,
      "message": "We got CI fixed via https://review.opendev.org/c/jjb/python-jenkins/+/865776 (which I approved after I got ping on IRC earlier today).\n\nIt is now failing on lines being too long which should be able to reproduce locally by running:\n\n tox -e linters\n\nAs for reviewing the code itself, it will need a bit of a time since this repository is not that active anymore. I will look at doing a pass of review over the week-end.",
      "parentUuid": "244508c1_ffdd1465",
      "revId": "f86c9161209f1a13cf91a33f706b03734b76f100",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b0f9f204_143e0f5c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 35866
      },
      "writtenOn": "2023-03-21T11:15:41Z",
      "side": 1,
      "message": "Yes, I will push the changes after fixing the issue.\nCertainly, please inform me if any further changes are necessary during your review of the code.",
      "parentUuid": "3e46ae6e_fd285879",
      "revId": "f86c9161209f1a13cf91a33f706b03734b76f100",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}